version: "3.8"

services:
  server:
    environment:
      - FLIX_MONGODB_URL=${FLIX_MONGODB_URL}
      - FLIX_SERVER_PORT=${FLIX_SERVER_PORT}
      - NODE_ENV="dev"
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: flix-server-dev
    ports:
      - "${FLIX_SERVER_PORT}:${FLIX_SERVER_PORT}"
    volumes:
      - ./api:/api
      - /api/node_modules
